### ISSUE TITLE
pbr dependency missing (needed for shooter provider)

### ISSUE THREAD

**Issue by msdos** [queeup-archives/repository.queeup#6]
```
ERROR:subliminal.core:Unexpected error in provider 'shooter'
Traceback (most recent call last):
  File "/storage/.xbmc/addons/shell.python.subliminal/resources/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/storage/.xbmc/addons/shell.python.subliminal/resources/lib/subliminal/providers/shooter.py", line 72, in list_subtitles
    return [s for l in languages for s in self.query(l, video.name, video.hashes.get('shooter'))]
  File "/storage/.xbmc/addons/shell.python.subliminal/resources/lib/subliminal/providers/shooter.py", line 55, in query
    params = {'filehash': hash, 'pathinfo': os.path.realpath(filename), 'format': 'json', 'lang': language.shooter}
  File "/storage/.xbmc/addons/shell.python.subliminal/resources/lib/babelfish/language.py", line 150, in __getattr__
    return language_converters[name].convert(alpha3, country, script)
  File "/storage/.xbmc/addons/shell.python.subliminal/resources/lib/babelfish/converters/__init__.py", line 240, in __getitem__
    self.converters[ep.name] = ep.load()()
  File "/storage/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2315, in load
    self.require(*args, **kwargs)
  File "/storage/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/storage/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'pbr>=1.6' distribution was not found and is required by stevedore
```

**Comment by queeup** [comment]
Fixed with version 2.1.0 of subliminal: 0bd32cd
